apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-creator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-creator
  template:
    metadata:
      labels:
        app: pod-creator
    spec:
      serviceAccountName: pod-creator-sa
      containers:
      - name: webservice
        image: pod-creator-webservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace

---
apiVersion: v1
kind: Service
metadata:
  name: pod-creator-service
spec:
  type: NodePort
  selector:
    app: pod-creator
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001